<a href="https://colab.research.google.com/github/Chi123Zhang/Finance-Research/blob/main/LLM%20reason.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [205]:
# =========================
# 0) Setup: clone repo
# =========================
REPO_URL = "https://github.com/Chi123Zhang/Finance-Research.git"
REPO_DIR = "Finance-Research"

from pathlib import Path
import os

if not Path(REPO_DIR).exists():
    !git clone {REPO_URL}

%cd {REPO_DIR}
!ls -lh

Cloning into 'Finance-Research'...
remote: Enumerating objects: 110, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (89/89), done.
remote: Total 110 (delta 24), reused 88 (delta 15), pack-reused 0 (from 0)
Receiving objects: 100% (110/110), 1.43 MiB | 24.35 MiB/s, done.
Resolving deltas: 100% (24/24), done.
/content/Finance-Research/Finance-Research/Finance-Research/Finance-Research
total 28K
drwxr-xr-x 2 root root 4.0K Mar  5 15:26 app
drwxr-xr-x 5 root root 4.0K Mar  5 15:26 chunk
drwxr-xr-x 7 root root 4.0K Mar  5 15:26 data
drwxr-xr-x 2 root root 4.0K Mar  5 15:26 llm
-rw-r--r-- 1 root root   18 Mar  5 15:26 README.md
-rw-r--r-- 1 root root  909 Mar  5 15:26 run_all.py
drwxr-xr-x 3 root root 4.0K Mar  5 15:26 strategy

In [206]:
# =========================
# 1) Load monthly_chunks + feature matrix
# =========================
import pandas as pd
import numpy as np

CHUNKS_PATH = Path("chunk/sample/monthly_chunks.parquet")
X_PATH      = Path("chunk/sample/monthly_feat_matrix.npy")

assert CHUNKS_PATH.exists(), f"Missing: {CHUNKS_PATH}"
assert X_PATH.exists(), f"Missing: {X_PATH}"

monthly_chunks = pd.read_parquet(CHUNKS_PATH)
X = np.load(X_PATH)

print("monthly_chunks:", monthly_chunks.shape)
print("X:", X.shape)
monthly_chunks.head()

monthly_chunks: (420, 30)
X: (420, 17)

,symbol,month,start_date,end_date,n_days,curve_logret,curve_cum,feat_month_ret,feat_month_vol,feat_month_mdd,...,ctx_unemployment_change_mean,ctx_unemployment_change_end,ctx_unemployment_change_chg,ctx_pe_ratio_end,ctx_ps_ratio_end,ctx_rev_growth_qoq_end,ctx_volume_change_end,label_next_month_ret,label_next_month_mdd,feat_vec
0,AAPL,2021-07,2021-07-03,2021-07-31,29,"[0.0, 0.0, 0.0, 0.0146112252544602, 0.01779592...","[1.0, 1.0, 1.0, 1.0, 1.0147184909974278, 1.032...",0.042155,0.178651,-0.044921,...,0.0,0.0,0.0,6.172662e-09,1.628193e-09,0.000000,-1.000000,0.040930,-0.031498,"[0.22477113097898765, -0.5335889694717059, 0.5..."
1,AAPL,2021-08,2021-08-01,2021-08-31,31,"[0.0, -0.0023337233462202, 0.0125650382971298,...","[1.0, 1.0, 0.9976689976689976, 1.0102838338132...",0.040930,0.151949,-0.031498,...,0.0,0.0,0.0,6.425307e-09,1.694834e-09,0.000000,0.708916,-0.068037,-0.096943,"[0.21599984617952556, -0.6411139230448345, 0.7..."
2,AAPL,2021-09,2021-09-01,2021-09-30,30,"[0.0044686937739958, 0.0074471209084012, 0.004...","[1.0, 1.0044786932753735, 1.0119870908252648, ...",-0.068037,0.171650,-0.096943,...,0.0,0.0,0.0,6.507542e-09,1.737603e-09,-0.090976,0.443733,0.058657,-0.024606,"[-0.5640694132485541, -0.5617820137476452, 0.0..."
3,AAPL,2021-10,2021-10-01,2021-10-31,31,"[0.0080943605762167, 0.0, 0.0, -0.024913457164...","[1.0, 1.0081272084805655, 1.0081272084805655, ...",0.058657,0.152249,-0.024606,...,0.0,0.0,0.0,6.889257e-09,1.839526e-09,-0.090976,-1.000000,0.103471,-0.031678,"[0.3429083217380599, -0.6399068945017538, 0.78..."
4,AAPL,2021-11,2021-11-01,2021-11-30,30,"[-0.0056232575543622, 0.0070908050127334, 0.00...","[1.0, 0.9943925233644859, 1.0014686248331108, ...",0.103471,0.192010,-0.031678,...,0.0,0.0,0.0,7.602097e-09,2.029865e-09,-0.090976,1.926668,0.074229,-0.054054,"[0.6637237543031062, -0.47979520314802615, 0.7..."

In [207]:
# =========================
# 2) Build cosine KNN index
# =========================
from sklearn.neighbors import NearestNeighbors

# cosine distance: smaller is more similar; we will convert to similarity = 1 - dist
nn = NearestNeighbors(n_neighbors=50, metric="cosine")
nn.fit(X)

print("✅ KNN index built.")

✅ KNN index built.

In [208]:
# =========================
# 3) Query function: find Top-K similar months + build evidence + build compare table
# =========================
import numpy as np

def query_similar(symbol: str, month: str, k: int = 10, exclude_self: bool = True):
    """
    symbol: e.g. "AAPL"
    month:  e.g. "2024-11"
    returns:
      res: DataFrame with top-k similar rows
      evidence: dict contains query/top1 meta + curves
    """
    mask = (monthly_chunks["symbol"] == symbol) & (monthly_chunks["month"] == month)
    if mask.sum() == 0:
        raise ValueError(f"Cannot find chunk for {symbol} {month}. Check available months.")

    q_idx = int(np.where(mask.to_numpy())[0][0])
    q_vec = X[q_idx].reshape(1, -1)

    # get more neighbors then filter self
    dist, idx = nn.kneighbors(q_vec, n_neighbors=max(k + 5, 20))
    idx = idx.flatten()
    dist = dist.flatten()
    sim = 1 - dist  # cosine similarity

    out = []
    for i, s in zip(idx, sim):
        if exclude_self and i == q_idx:
            continue
        out.append((i, float(s)))
        if len(out) >= k:
            break

    # build result table
    rows = []
    for rank, (i, s) in enumerate(out, start=1):
        r = monthly_chunks.iloc[i]
        rows.append({
            "rank": rank,
            "similarity": s,
            "symbol": r.get("symbol"),
            "month": r.get("month"),
            "start_date": r.get("start_date"),
            "end_date": r.get("end_date"),
            # some common feature cols (if exist)
            "feat_month_ret": r.get("feat_month_ret", np.nan),
            "feat_month_vol": r.get("feat_month_vol", np.nan),
            "feat_month_mdd": r.get("feat_month_mdd", np.nan),
            "feat_trend_slope": r.get("feat_trend_slope", np.nan),
            "label_next_month_ret": r.get("label_next_month_ret", np.nan),
        })
    res = pd.DataFrame(rows)

    # evidence curves (used for plotting / debugging)
    q_row = monthly_chunks.iloc[q_idx]
    top1_i = out[0][0]
    top1_row = monthly_chunks.iloc[top1_i]

    q_curve = np.array(q_row["curve_cum"], dtype=float)
    t_curve = np.array(top1_row["curve_cum"], dtype=float)

    # normalize start=1
    q_curve = q_curve / (q_curve[0] if q_curve[0] != 0 else 1.0)
    t_curve = t_curve / (t_curve[0] if t_curve[0] != 0 else 1.0)

    evidence = {
        "query": {"symbol": symbol, "month": month},
        "top1": {"symbol": top1_row["symbol"], "month": top1_row["month"], "similarity": out[0][1]},
        "q_curve": q_curve,
        "top1_curve": t_curve,
        "q_idx": q_idx,
        "top1_idx": int(top1_i),
    }
    return res, evidence


def build_compare_table(monthly_chunks: pd.DataFrame, evidence: dict) -> pd.DataFrame:
    """
    Create the Query vs Top1 feature compare table like your screenshot.
    index: feature name
    cols:  Query, Top1
    """
    q_idx = evidence["q_idx"]
    t_idx = evidence["top1_idx"]
    q_row = monthly_chunks.iloc[q_idx]
    t_row = monthly_chunks.iloc[t_idx]

    # choose columns: ctx_* plus selected feat_*
    wanted = [c for c in monthly_chunks.columns if c.startswith("ctx_")]
    wanted += [
        "feat_month_ret", "feat_month_vol", "feat_month_mdd", "feat_trend_slope",
        "feat_ret_first_half", "feat_ret_second_half", "feat_vol20_chg",
    ]
    # keep only existing
    wanted = [c for c in wanted if c in monthly_chunks.columns]

    compare = pd.DataFrame({
        "Query": [q_row[c] for c in wanted],
        "Top1":  [t_row[c] for c in wanted],
    }, index=wanted)

    # make sure numeric where possible
    compare["Query"] = pd.to_numeric(compare["Query"], errors="coerce")
    compare["Top1"] = pd.to_numeric(compare["Top1"], errors="coerce")

    return compare

In [209]:
# =========================
# 4) Pick which (symbol, month) you want -> generate compare.csv automatically
# =========================
QUERY_SYMBOL = "AAPL"
QUERY_MONTH  = "2024-11"
K = 10

res, evidence = query_similar(QUERY_SYMBOL, QUERY_MONTH, k=K)
display(res)

compare = build_compare_table(monthly_chunks, evidence)
display(compare)

# save compare.csv into repo
OUT_COMPARE = Path("chunk/sample/compare.csv")
compare.to_csv(OUT_COMPARE)
print("✅ saved:", OUT_COMPARE, " shape:", compare.shape)

,rank,similarity,symbol,month,start_date,end_date,feat_month_ret,feat_month_vol,feat_month_mdd,feat_trend_slope,label_next_month_ret
0,1,0.915144,MSFT,2024-11,2024-11-01,2024-11-30,0.042107,0.149969,-0.032842,0.416760,-0.004629
1,2,0.773160,TSM,2023-03,2023-03-01,2023-03-31,0.068336,0.226279,-0.045470,0.672630,-0.093743
2,3,0.772982,GOOGL,2023-12,2023-12-01,2023-12-31,0.054026,0.200612,-0.036442,0.841226,0.002935
3,4,0.733556,GOOGL,2024-06,2024-06-01,2024-06-30,0.055942,0.140193,-0.017583,0.880094,-0.058249
4,5,0.721462,QCOM,2023-12,2023-12-01,2023-12-31,0.120728,0.146859,-0.019479,0.935257,0.026827
5,6,0.718059,TXN,2023-03,2023-03-01,2023-03-31,0.084923,0.178343,-0.025990,0.786893,-0.101124
6,7,0.717160,MSFT,2023-12,2023-12-01,2023-12-31,-0.007574,0.114457,-0.034256,0.396680,0.057281
7,8,0.710325,AAPL,2023-03,2023-03-01,2023-03-31,0.118649,0.187231,-0.034649,0.907027,0.028987
8,9,0.696421,GOOGL,2023-07,2023-07-01,2023-07-31,0.108772,0.259220,-0.049593,0.712301,0.025995
9,10,0.694582,MSFT,2023-03,2023-03-01,2023-03-31,0.155882,0.221252,-0.032234,0.889773,0.065765

                                     Query          Top1
ctx_real_rate_mean            5.236616e-01  5.236616e-01
ctx_real_rate_end             5.236616e-01  5.236616e-01
ctx_real_rate_chg             0.000000e+00  0.000000e+00
ctx_yield_curve_mean         -2.800000e-01 -2.800000e-01
ctx_yield_curve_end          -2.800000e-01 -2.800000e-01
ctx_yield_curve_chg           0.000000e+00  0.000000e+00
ctx_unemployment_change_mean -7.936508e-04 -7.936508e-04
ctx_unemployment_change_end   0.000000e+00  0.000000e+00
ctx_unemployment_change_chg   2.380952e-02  2.380952e-02
ctx_pe_ratio_end              1.106537e-08  1.921674e-08
ctx_ps_ratio_end              2.766826e-09  6.542247e-09
ctx_rev_growth_qoq_end       -5.483014e-02  4.638042e-02
ctx_volume_change_end        -1.000000e+00 -1.000000e+00
feat_month_ret                5.055110e-02  4.210656e-02
feat_month_vol                1.218149e-01  1.499686e-01
feat_month_mdd               -1.726351e-02 -3.284218e-02
feat_trend_slope              8.971617e-01  4.167599e-01
feat_ret_first_half          -4.028153e-03  2.128707e-02
feat_ret_second_half          5.480000e-02  2.038554e-02
feat_vol20_chg               -2.770167e-03 -5.820571e-03

✅ saved: chunk/sample/compare.csv  shape: (20, 2)

In [210]:
print(compare.columns)

Index(['Query', 'Top1'], dtype='object')

In [211]:
print(res.columns)
print(res.head())

Index(['rank', 'similarity', 'symbol', 'month', 'start_date', 'end_date',
       'feat_month_ret', 'feat_month_vol', 'feat_month_mdd',
       'feat_trend_slope', 'label_next_month_ret'],
      dtype='object')
   rank  similarity symbol    month start_date   end_date  feat_month_ret  \
0     1    0.915144   MSFT  2024-11 2024-11-01 2024-11-30        0.042107
1     2    0.773160    TSM  2023-03 2023-03-01 2023-03-31        0.068336
2     3    0.772982  GOOGL  2023-12 2023-12-01 2023-12-31        0.054026
3     4    0.733556  GOOGL  2024-06 2024-06-01 2024-06-30        0.055942
4     5    0.721462   QCOM  2023-12 2023-12-01 2023-12-31        0.120728

   feat_month_vol  feat_month_mdd  feat_trend_slope  label_next_month_ret
0        0.149969       -0.032842          0.416760             -0.004629
1        0.226279       -0.045470          0.672630             -0.093743
2        0.200612       -0.036442          0.841226              0.002935
3        0.140193       -0.017583          0.880094             -0.058249
4        0.146859       -0.019479          0.935257              0.026827

In [212]:
import pandas as pd

# 1) Segment 2：严格用 query_symbol + query_month 在 monthly_chunks 里定位
q = monthly_chunks[(monthly_chunks["symbol"] == QUERY_SYMBOL) & (monthly_chunks["month"] == QUERY_MONTH)]
if q.empty:
    raise ValueError(f"Query not found in monthly_chunks: {QUERY_SYMBOL} {QUERY_MONTH}")

qrow = q.iloc[0]
seg2 = {
    "symbol": QUERY_SYMBOL,
    "start": pd.to_datetime(qrow["start_date"]),
    "end": pd.to_datetime(qrow["end_date"]),
}

# 2) Segment 1：从 res 里挑“历史最相似”，排除同 symbol & 同 month（避免拿自己/同月）
seg1_row = None
for _, row in res.iterrows():
    if (row["symbol"] == QUERY_SYMBOL) and (row["month"] == QUERY_MONTH):
        continue
    # 你也可以只排除同 month：if row["month"] == QUERY_MONTH: continue
    seg1_row = row
    break

if seg1_row is None:
    raise ValueError("No suitable historical segment found in res.")

seg1 = {
    "symbol": seg1_row["symbol"],
    "start": pd.to_datetime(seg1_row["start_date"]),
    "end": pd.to_datetime(seg1_row["end_date"]),
}

print("Segment 1:", seg1)
print("Segment 2:", seg2)

Segment 1: {'symbol': 'MSFT', 'start': Timestamp('2024-11-01 00:00:00'), 'end': Timestamp('2024-11-30 00:00:00')}
Segment 2: {'symbol': 'AAPL', 'start': Timestamp('2024-11-01 00:00:00'), 'end': Timestamp('2024-11-30 00:00:00')}

In [213]:
# =========================
# 5) Build Segments (two companies, same month)
# =========================

segments = [
    {
        "segment_id": 1,
        "symbol": seg1["symbol"],
        "start_date": seg1["start"].strftime("%Y-%m-%d"),
        "end_date": seg1["end"].strftime("%Y-%m-%d"),
    },
    {
        "segment_id": 2,
        "symbol": seg2["symbol"],
        "start_date": seg2["start"].strftime("%Y-%m-%d"),
        "end_date": seg2["end"].strftime("%Y-%m-%d"),
    },
]

print("Segments:\n", segments)


print(f"""
Segment 1:
{seg1['symbol']} {seg1['start'].strftime('%Y-%m-%d')} → {seg1['end'].strftime('%Y-%m-%d')}

Segment 2:
{seg2['symbol']} {seg2['start'].strftime('%Y-%m-%d')} → {seg2['end'].strftime('%Y-%m-%d')}
""")

Segments:
 [{'segment_id': 1, 'symbol': 'MSFT', 'start_date': '2024-11-01', 'end_date': '2024-11-30'}, {'segment_id': 2, 'symbol': 'AAPL', 'start_date': '2024-11-01', 'end_date': '2024-11-30'}]

Segment 1:
MSFT 2024-11-01 → 2024-11-30

Segment 2:
AAPL 2024-11-01 → 2024-11-30

In [214]:
def build_llm_table(seg1, seg2, compare: pd.DataFrame):

    rows = []

    r1 = {
        "segment_id": 1,
        "company": f"{seg1['symbol']} (Top1)",
        "start_date": seg1["start"].strftime("%Y-%m-%d"),
        "end_date": seg1["end"].strftime("%Y-%m-%d"),
    }

    r2 = {
        "segment_id": 2,
        "company": f"{seg2['symbol']} (Query)",
        "start_date": seg2["start"].strftime("%Y-%m-%d"),
        "end_date": seg2["end"].strftime("%Y-%m-%d"),
    }

    for feat in compare.index:
        r1[feat] = float(compare.loc[feat, "Top1"])
        r2[feat] = float(compare.loc[feat, "Query"])

    rows.append(r1)
    rows.append(r2)

    return pd.DataFrame(rows)
segment_df = build_llm_table(seg1, seg2, compare)
segment_df = build_llm_table(seg1, seg2, compare)

print(segment_df)

   segment_id       company  start_date    end_date  ctx_real_rate_mean  \
0           1   MSFT (Top1)  2024-11-01  2024-11-30            0.523662
1           2  AAPL (Query)  2024-11-01  2024-11-30            0.523662

   ctx_real_rate_end  ctx_real_rate_chg  ctx_yield_curve_mean  \
0           0.523662                0.0                 -0.28
1           0.523662                0.0                 -0.28

   ctx_yield_curve_end  ctx_yield_curve_chg  ...  ctx_ps_ratio_end  \
0                -0.28                  0.0  ...      6.542247e-09
1                -0.28                  0.0  ...      2.766826e-09

   ctx_rev_growth_qoq_end  ctx_volume_change_end  feat_month_ret  \
0                 0.04638                   -1.0        0.042107
1                -0.05483                   -1.0        0.050551

   feat_month_vol  feat_month_mdd  feat_trend_slope  feat_ret_first_half  \
0        0.149969       -0.032842          0.416760             0.021287
1        0.121815       -0.017264          0.897162            -0.004028

   feat_ret_second_half  feat_vol20_chg
0              0.020386       -0.005821
1              0.054800       -0.002770

[2 rows x 24 columns]

In [215]:
segment_table_md = segment_df.to_markdown(index=False)
print(segment_table_md)

|   segment_id | company      | start_date   | end_date   |   ctx_real_rate_mean |   ctx_real_rate_end |   ctx_real_rate_chg |   ctx_yield_curve_mean |   ctx_yield_curve_end |   ctx_yield_curve_chg |   ctx_unemployment_change_mean |   ctx_unemployment_change_end |   ctx_unemployment_change_chg |   ctx_pe_ratio_end |   ctx_ps_ratio_end |   ctx_rev_growth_qoq_end |   ctx_volume_change_end |   feat_month_ret |   feat_month_vol |   feat_month_mdd |   feat_trend_slope |   feat_ret_first_half |   feat_ret_second_half |   feat_vol20_chg |
|-------------:|:-------------|:-------------|:-----------|---------------------:|--------------------:|--------------------:|-----------------------:|----------------------:|----------------------:|-------------------------------:|------------------------------:|------------------------------:|-------------------:|-------------------:|-------------------------:|------------------------:|-----------------:|-----------------:|-----------------:|-------------------:|----------------------:|-----------------------:|-----------------:|
|            1 | MSFT (Top1)  | 2024-11-01   | 2024-11-30 |             0.523662 |            0.523662 |                   0 |                  -0.28 |                 -0.28 |                     0 |                   -0.000793651 |                             0 |                     0.0238095 |        1.92167e-08 |        6.54225e-09 |                0.0463804 |                      -1 |        0.0421066 |         0.149969 |       -0.0328422 |           0.41676  |            0.0212871  |              0.0203855 |      -0.00582057 |
|            2 | AAPL (Query) | 2024-11-01   | 2024-11-30 |             0.523662 |            0.523662 |                   0 |                  -0.28 |                 -0.28 |                     0 |                   -0.000793651 |                             0 |                     0.0238095 |        1.10654e-08 |        2.76683e-09 |               -0.0548301 |                      -1 |        0.0505511 |         0.121815 |       -0.0172635 |           0.897162 |           -0.00402815 |              0.0548    |      -0.00277017 |

In [216]:
from pathlib import Path

def build_market_prompt(segment_table_md: str) -> str:
    return f"""
You are a quantitative market strategist writing an institutional-style market commentary.

Write analysis for TWO market segments.

IMPORTANT RULES
Output plain text only. Bullet points using "-" are allowed.
Do not output reasoning steps.
Use only numerical values from the table.
Round numbers to 2 decimals.
Write numbers as decimals (do not convert to percentages).
Follow the structure exactly.

You may include qualitative macro interpretation such as:

- monetary policy conditions
- discount rate environment
- investor risk appetite
- technology sector sentiment
- institutional capital flows into large-cap technology stocks

Do not introduce numerical values that are not present in the table.

Segment mapping
Segment 1 = Top1 similar segment
Segment 2 = Query segment

STRUCTURE

Segment X: company, start_date to end_date

Paragraph 1 — Market Regime
Describe the macroeconomic regime and investor sentiment during the period.
Mention technology sector positioning and general market stability.

Paragraph 2 — Price Dynamics
Explain price behavior using feat_month_ret and the overall trend.

Paragraph 3 — Macro Conditions
Interpret the macro indicators:

Real interest rate ≈ ctx_real_rate_mean
Yield curve ≈ ctx_yield_curve_mean
Unemployment change ≈ ctx_unemployment_change_mean

Explain what these indicators imply about discount rates and economic stability.

Paragraph 4 — Equity Market Implications
Explain how this macro regime influences investor positioning,
risk appetite, and capital flows toward large-cap technology stocks.

Paragraph 5 — Market Statistics
Introduce the statistical profile, then list:

- Monthly return ≈ feat_month_ret
- Monthly volatility ≈ feat_month_vol
- Maximum drawdown ≈ feat_month_mdd
- Trend slope ≈ feat_trend_slope

Paragraph 6 — Risk-Return Interpretation
Explain the asset’s momentum strength, downside risk,
and overall risk-return profile.

IMPORTANT FOR SEGMENT 2

Do NOT repeat Segment 1 wording.
Highlight differences in market behavior, especially trend slope
(feat_trend_slope) and volatility.

FINAL PARAGRAPH (Segment 2 only)

Explain why Segment 2 is similar to Segment 1.

This explanation must be at least 60 words and must:

- compare macro indicators
  (ctx_real_rate_mean, ctx_yield_curve_mean, ctx_unemployment_change_mean)

- compare market indicators
  (feat_month_ret, feat_month_vol, feat_month_mdd, feat_trend_slope)

- explain the economic mechanism behind the similarity,
  such as shared discount-rate environments,
  synchronized capital flows,
  or comparable volatility regimes.

Write Segment 1 first, then Segment 2.

Data:
{segment_table_md}
""".strip()

prompt = build_market_prompt(segment_table_md)
Path("prompt.txt").write_text(prompt, encoding="utf-8")
print("prompt saved")

prompt saved

In [217]:
from huggingface_hub import hf_hub_download

repo_id = "unsloth/Qwen3.5-35B-A3B-GGUF"
filename = "Qwen3.5-35B-A3B-Q4_K_M.gguf"

local_path = hf_hub_download(
    repo_id=repo_id,
    filename=filename
)

In [218]:
# =========================
# 8) (Optional) Run local LLM with llama.cpp -> analysis.md
#    如果你还没有 gguf 模型，先跳过这一格
# =========================
from pathlib import Path

# Build llama.cpp if needed
if not Path("llama.cpp").exists():
    !git clone https://github.com/ggerganov/llama.cpp

%cd llama.cpp
!cmake -B build -DGGML_CUDA=ON
!cmake --build build -j
%cd ..

# >>> IMPORTANT: Set your local gguf model path here <<<
MODEL_PATH = "/root/.cache/huggingface/hub/models--unsloth--Qwen3.5-35B-A3B-GGUF/snapshots/0da7d49832a73abe50f0c89070971b59dad0039d/Qwen3.5-35B-A3B-Q4_K_M.gguf"

assert Path(MODEL_PATH).exists(), f"❌ MODEL_PATH not found: {MODEL_PATH}"

Cloning into 'llama.cpp'...
remote: Enumerating objects: 81823, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (116/116), done.
remote: Total 81823 (delta 50), reused 14 (delta 12), pack-reused 81695 (from 3)
Receiving objects: 100% (81823/81823), 309.04 MiB | 42.47 MiB/s, done.
Resolving deltas: 100% (58828/58828), done.
/content/Finance-Research/Finance-Research/Finance-Research/Finance-Research/llama.cpp
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE=Release
-- Found Git: /usr/bin/git (found version "2.34.1")
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Warning: ccache not found - consider installing it for faster compilation or disable this warning with GGML_CCACHE=OFF
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- GGML_SYSTEM_ARCH: x86
-- Including CPU backend
-- Found OpenMP_C: -fopenmp (found version "4.5")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
-- x86 detected
-- Adding CPU backend variant ggml-cpu: -march=native
-- Found CUDAToolkit: /usr/local/cuda/targets/x86_64-linux/include (found version "12.8.93")
-- CUDA Toolkit found
-- The CUDA compiler identification is NVIDIA 12.8.93 with host compiler GNU 11.4.0
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Replacing 120-real in CMAKE_CUDA_ARCHITECTURES_NATIVE with 120a-real
-- Using CMAKE_CUDA_ARCHITECTURES=120a-real CMAKE_CUDA_ARCHITECTURES_NATIVE=120a-real
-- CUDA host compiler is GNU 11.4.0
-- Including CUDA backend
-- ggml version: 0.9.7
-- ggml commit:  a0ed91a44
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "3.0.2")
-- Performing Test OPENSSL_VERSION_SUPPORTED
-- Performing Test OPENSSL_VERSION_SUPPORTED - Success
-- OpenSSL found: 3.0.2
-- Generating embedded license file for target: common
-- Configuring done (4.0s)
-- Generating done (0.2s)
-- Build files have been written to: /content/Finance-Research/Finance-Research/Finance-Research/Finance-Research/llama.cpp/build
[  0%] Building CXX object common/CMakeFiles/build_info.dir/build-info.cpp.o
[  0%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml.c.o
[  0%] Building CXX object vendor/cpp-httplib/CMakeFiles/cpp-httplib.dir/httplib.cpp.o
[  0%] Building C object examples/gguf-hash/CMakeFiles/sha256.dir/deps/sha256/sha256.c.o
[  0%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml.cpp.o
[  1%] Building C object examples/gguf-hash/CMakeFiles/xxhash.dir/deps/xxhash/xxhash.c.o
[  1%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-alloc.c.o
[  1%] Building C object examples/gguf-hash/CMakeFiles/sha1.dir/deps/sha1/sha1.c.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-backend.cpp.o
[  2%] Building CXX object tools/mtmd/CMakeFiles/llama-llava-cli.dir/deprecation-warning.cpp.o
[  2%] Building CXX object tools/mtmd/CMakeFiles/llama-gemma3-cli.dir/deprecation-warning.cpp.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-opt.cpp.o
[  2%] Building CXX object tools/mtmd/CMakeFiles/llama-minicpmv-cli.dir/deprecation-warning.cpp.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/ggml-threading.cpp.o
[  2%] Building C object ggml/src/CMakeFiles/ggml-base.dir/ggml-quants.c.o
[  2%] Building CXX object tools/mtmd/CMakeFiles/llama-qwen2vl-cli.dir/deprecation-warning.cpp.o
[  2%] Building CXX object ggml/src/CMakeFiles/ggml-base.dir/gguf.cpp.o
[  2%] Built target build_info
[  2%] Built target sha1
[  2%] Linking CXX executable ../../bin/llama-llava-cli
[  2%] Linking CXX executable ../../bin/llama-minicpmv-cli
[  3%] Linking CXX executable ../../bin/llama-gemma3-cli
[  4%] Linking CXX executable ../../bin/llama-qwen2vl-cli
[  4%] Built target sha256
[  4%] Built target llama-llava-cli
[  4%] Built target llama-gemma3-cli
[  4%] Built target llama-minicpmv-cli
[  4%] Built target llama-qwen2vl-cli
[  4%] Built target xxhash
[  4%] Linking CXX shared library ../../bin/libggml-base.so
[  4%] Built target ggml-base
[  5%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.c.o
[  5%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/repack.cpp.o
[  5%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/hbm.cpp.o
[  6%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/quants.c.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/traits.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ggml-cpu.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/amx.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/amx/mmq.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/binary-ops.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/unary-ops.cpp.o
[  6%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/vec.cpp.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/ops.cpp.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/llamafile/sgemm.cpp.o
[  7%] Building C object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/x86/quants.c.o
[  7%] Building CXX object ggml/src/CMakeFiles/ggml-cpu.dir/ggml-cpu/arch/x86/repack.cpp.o
[  7%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/acc.cu.o
[  8%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/add-id.cu.o
[  8%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/arange.cu.o
[  8%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/argmax.cu.o
[  8%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/argsort.cu.o
[  8%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/binbcast.cu.o
[  9%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/clamp.cu.o
[  9%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/concat.cu.o
[  9%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/conv2d-transpose.cu.o
[  9%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/conv-transpose-1d.cu.o
[  9%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/conv2d-dw.cu.o
[ 10%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/conv2d.cu.o
[ 10%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/convert.cu.o
[ 10%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/count-equal.cu.o
[ 10%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/cpy.cu.o
[ 10%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/cross-entropy-loss.cu.o
[ 10%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/cumsum.cu.o
[ 10%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/diag.cu.o
[ 11%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/diagmask.cu.o
[ 11%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/fattn-tile.cu.o
[ 11%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/fattn-wmma-f16.cu.o
[ 11%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/fill.cu.o
[ 11%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/fattn.cu.o
[ 12%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/getrows.cu.o
[ 12%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/ggml-cuda.cu.o
[ 12%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/gla.cu.o
[ 12%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/im2col.cu.o
[ 12%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/mean.cu.o
[ 12%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/mmf.cu.o
[ 13%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/mmq.cu.o
[ 13%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/mmid.cu.o
[ 13%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/mmvf.cu.o
[ 13%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/mmvq.cu.o
[ 13%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/norm.cu.o
[ 13%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/opt-step-adamw.cu.o
[ 14%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/opt-step-sgd.cu.o
[ 14%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/out-prod.cu.o
[ 14%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/pad.cu.o
[ 14%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/pad_reflect_1d.cu.o
[ 15%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/quantize.cu.o
[ 15%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/pool2d.cu.o
[ 15%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/roll.cu.o
[ 15%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/rope.cu.o
[ 15%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/scale.cu.o
[ 15%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/set-rows.cu.o
[ 15%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/set.cu.o
[ 16%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/softcap.cu.o
[ 16%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/softmax.cu.o
[ 16%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/solve_tri.cu.o
[ 16%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/ssm-scan.cu.o
[ 16%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/ssm-conv.cu.o
[ 17%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/sum.cu.o
[ 17%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/sumrows.cu.o
[ 17%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/top-k.cu.o
[ 17%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/topk-moe.cu.o
[ 17%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/tri.cu.o
[ 17%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/tsembd.cu.o
[ 18%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/unary.cu.o
[ 18%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/upscale.cu.o
[ 18%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/wkv.cu.o
[ 18%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-tile-instance-dkq112-dv112.cu.o
[ 18%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-tile-instance-dkq128-dv128.cu.o
[ 18%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-tile-instance-dkq256-dv256.cu.o
[ 19%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-tile-instance-dkq40-dv40.cu.o
[ 19%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-tile-instance-dkq576-dv512.cu.o
[ 19%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-tile-instance-dkq64-dv64.cu.o
[ 19%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-tile-instance-dkq72-dv72.cu.o
[ 19%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-tile-instance-dkq80-dv80.cu.o
[ 20%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-tile-instance-dkq96-dv96.cu.o
[ 20%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_1-ncols2_16.cu.o
[ 20%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_1-ncols2_32.cu.o
[ 20%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_1-ncols2_8.cu.o
[ 20%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_16-ncols2_1.cu.o
[ 20%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_16-ncols2_2.cu.o
[ 21%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_16-ncols2_4.cu.o
[ 21%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_2-ncols2_16.cu.o
[ 21%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_2-ncols2_32.cu.o
[ 21%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_2-ncols2_4.cu.o
[ 21%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_2-ncols2_8.cu.o
[ 21%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_32-ncols2_1.cu.o
[ 22%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_32-ncols2_2.cu.o
[ 22%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_4-ncols2_16.cu.o
[ 22%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_4-ncols2_2.cu.o
[ 22%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_4-ncols2_8.cu.o
[ 22%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_4-ncols2_4.cu.o
[ 23%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_64-ncols2_1.cu.o
[ 23%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_8-ncols2_1.cu.o
[ 23%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_8-ncols2_2.cu.o
[ 23%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_8-ncols2_4.cu.o
[ 23%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-mma-f16-instance-ncols1_8-ncols2_8.cu.o
[ 23%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-iq1_s.cu.o
[ 23%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-iq2_xs.cu.o
[ 24%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-iq2_s.cu.o
[ 24%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-iq2_xxs.cu.o
[ 24%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-iq3_s.cu.o
[ 24%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-iq3_xxs.cu.o
[ 24%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-iq4_nl.cu.o
[ 25%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-iq4_xs.cu.o
[ 25%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q3_k.cu.o
[ 25%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-mxfp4.cu.o
[ 25%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q4_0.cu.o
[ 25%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q2_k.cu.o
[ 26%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q4_1.cu.o
[ 26%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q5_0.cu.o
[ 26%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q4_k.cu.o
[ 26%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q5_k.cu.o
[ 27%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q8_0.cu.o
[ 27%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q6_k.cu.o
[ 27%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_1.cu.o
[ 27%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmq-instance-q5_1.cu.o
[ 27%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_10.cu.o
[ 27%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_11.cu.o
[ 27%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_12.cu.o
[ 27%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_13.cu.o
[ 28%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_14.cu.o
[ 28%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_15.cu.o
[ 28%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_16.cu.o
[ 28%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_2.cu.o
[ 28%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_3.cu.o
[ 29%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_4.cu.o
[ 29%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_5.cu.o
[ 29%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_6.cu.o
[ 29%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_8.cu.o
[ 29%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_7.cu.o
[ 29%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/mmf-instance-ncols_9.cu.o
[ 30%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-vec-instance-q4_0-q4_0.cu.o
[ 30%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-vec-instance-f16-f16.cu.o
[ 30%] Building CUDA object ggml/src/ggml-cuda/CMakeFiles/ggml-cuda.dir/template-instances/fattn-vec-instance-q8_0-q8_0.cu.o
[ 30%] Linking CXX shared library ../../bin/libggml-cpu.so
[ 30%] Built target ggml-cpu
[ 30%] Linking CXX static library libcpp-httplib.a
[ 30%] Built target cpp-httplib
[ 30%] Linking CUDA shared library ../../../bin/libggml-cuda.so
[ 30%] Built target ggml-cuda
[ 31%] Building CXX object ggml/src/CMakeFiles/ggml.dir/ggml-backend-dl.cpp.o

In [219]:
!./llama.cpp/build/bin/llama-cli \
  -m "{MODEL_PATH}" \
  -f prompt.txt \
  -c 8192 \
  -ngl 50 \
  --temp 0.0 \
  2>&1 | tee analysis.md

ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA RTX PRO 6000 Blackwell Server Edition, compute capability 12.0, VMM: yes

Loading model... |-\|/-\|/-\|/-\|/-\|/-\ 


▄▄ ▄▄
██ ██
██ ██  ▀▀█▄ ███▄███▄  ▀▀█▄    ▄████ ████▄ ████▄
██ ██ ▄█▀██ ██ ██ ██ ▄█▀██    ██    ██ ██ ██ ██
██ ██ ▀█▄██ ██ ██ ██ ▀█▄██ ██ ▀████ ████▀ ████▀
                                    ██    ██
                                    ▀▀    ▀▀

build      : b8211-a0ed91a44
model      : Qwen3.5-35B-A3B-Q4_K_M.gguf
modalities : text

available commands:
  /exit or Ctrl+C     stop or exit
  /regen              regenerate the last response
  /clear              clear the chat history
  /read               add a text file


> You are a quantitative market strategist writing an institutional-style market commentary.

Write analysis for TWO market segments.

IMPORTANT RULES
Output plain text only. Bullet points using "-" are allowed.
Do not output reasoning steps.
Use only numerical values from the table.
Round numbers to 2 decimals.
Write numbers as decimals (do not convert to percentages).
Follow the structure exactly.

You may include qualitative macro interpretation such as:

- monetary policy conditions
- discount ... (truncated)

|-\ Thinking Process:

1.  **Analyze the Request:**
    *   **Role:** Quantitative market strategist writing an institutional-style market commentary.
    *   **Task:** Write analysis for TWO market segments (Segment 1 = Top1, Segment 2 = Query).
    *   **Input Data:** A table containing data for MSFT (Segment 1) and AAPL (Segment 2) for the period 2024-11-01 to 2024-11-30.
    *   **Constraints:**
        *   Output plain text only.
        *   Bullet points using "-" are allowed.
        *   Do not output reasoning steps.
        *   Use *only* numerical values from the table.
        *   Round numbers to 2 decimals.
        *   Write numbers as decimals (do not convert to percentages).
        *   Follow the structure exactly (6 paragraphs per segment + final comparison paragraph for Segment 2).
        *   Segment 1: Standard structure.
        *   Segment 2: Standard structure + Final Paragraph (60+ words, comparing macro and market indicators, explaining economic mechanism).
        *   Do not repeat Segment 1 wording in Segment 2.
        *   Highlight differences in Segment 2 (trend slope, volatility).

2.  **Extract Data:**

    *   **Segment 1 (MSFT):**
        *   Company: MSFT
        *   Dates: 2024-11-01 to 2024-11-30
        *   ctx_real_rate_mean: 0.523662 -> 0.52
        *   ctx_yield_curve_mean: -0.28 -> -0.28
        *   ctx_unemployment_change_mean: -0.000793651 -> -0.00
        *   feat_month_ret: 0.0421066 -> 0.04
        *   feat_month_vol: 0.149969 -> 0.15
        *   feat_month_mdd: -0.0328422 -> -0.03
        *   feat_trend_slope: 0.41676 -> 0.42

    *   **Segment 2 (AAPL):**
        *   Company: AAPL
        *   Dates: 2024-11-01 to 2024-11-30
        *   ctx_real_rate_mean: 0.523662 -> 0.52
        *   ctx_yield_curve_mean: -0.28 -> -0.28
        *   ctx_unemployment_change_mean: -0.000793651 -> -0.00
        *   feat_month_ret: 0.0505511 -> 0.05
        *   feat_month_vol: 0.121815 -> 0.12
        *   feat_month_mdd: -0.0172635 -> -0.02
        *   feat_trend_slope: 0.897162 -> 0.90

3.  **Drafting Segment 1 (MSFT):**

    *   *Paragraph 1 (Market Regime):* Focus on macro regime, sentiment, tech positioning, stability.
    *   *Paragraph 2 (Price Dynamics):* Use feat_month_ret (0.04).
    *   *Paragraph 3 (Macro Conditions):* Use real rate (0.52), yield curve (-0.28), unemployment (-0.00). Discuss discount rates/economic stability.
    *   *Paragraph 4 (Equity Market Implications):* Investor positioning, risk appetite, flows to large-cap tech.
    *   *Paragraph 5 (Market Statistics):* List stats (ret, vol, mdd, slope).
    *   *Paragraph 6 (Risk-Return Interpretation):* Momentum, downside risk, profile.

4.  **Drafting Segment 2 (AAPL):**

    *   *Paragraph 1 (Market Regime):* Different wording than Seg 1. Focus on macro/sentiment.
    *   *Paragraph 2 (Price Dynamics):* Use feat_month_ret (0.05).
    *   *Paragraph 3 (Macro Conditions):* Same macro data (0.52, -0.28, -0.00). Discuss implications.
    *   *Paragraph 4 (Equity Market Implications):* Different wording. Positioning/flows.
    *   *Paragraph 5 (Market Statistics):* List stats (ret, vol, mdd, slope).
    *   *Paragraph 6 (Risk-Return Interpretation):* Momentum, downside risk, profile. Highlight differences (slope 0.90 vs 0.42, vol 0.12 vs 0.15).
    *   *Final Paragraph (Comparison):* Must be 60+ words. Compare macro (rates, yield, unemployment) and market (ret, vol, mdd, slope). Explain mechanism (discount rates, flows, volatility).

5.  **Refining Numbers:**
    *   Round to 2 decimals.
    *   Decimal format (e.g., 0.04, not 4%).
    *   Check specific values:
        *   MSFT Ret: 0.0421066 -> 0.04
        *   MSFT Vol: 0.149969 -> 0.15
        *   MSFT MDD: -0.0328422 -> -0.03
        *   MSFT Slope: 0.41676 -> 0.42
        *   AAPL Ret: 0.0505511 -> 0.05
        *   AAPL Vol: 0.121815 -> 0.12
        *   AAPL MDD: -0.0172635 -> -0.02
        *   AAPL Slope: 0.897162 -> 0.90
        *   Macro Rates: 0.523662 -> 0.52
        *   Macro Yield: -0.28 -> -0.28
        *   Macro Unemp: -0.000793651 -> -0.00

6.  **Writing Content (Iterative Check):**

    *   *Seg 1 Para 1:* During the period from 2024-11-01 to 2024-11-30, the market operated within a stable macroeconomic regime characterized by cautious investor sentiment. Technology sector positioning remained constructive as large-cap names attracted steady institutional capital flows. General market stability was maintained despite external volatility pressures.
    *   *Seg 1 Para 2:* Price behavior exhibited a positive trajectory with a monthly return of 0.04. The asset demonstrated resilience, capturing upside momentum while managing downside exposure effectively throughout the month.
    *   *Seg 1 Para 3:* Macro indicators reflected a neutral discount rate environment with a real interest rate of 0.52. The yield curve stood at -0.28, suggesting mild inversion, while unemployment change remained near -0.00. These conditions imply stable economic fundamentals with limited pressure on valuation multiples.
    *   *Seg 1 Para 4:* This macro regime supports risk-on positioning among institutional investors. Capital flows continue to favor large-cap technology stocks as discount rates remain contained. Investor risk appetite is sustained by the perceived safety of established market leaders.
    *   *Seg 1 Para 5:* The statistical profile indicates moderate volatility and controlled drawdowns.
        - Monthly return ≈ 0.04
        - Monthly volatility ≈ 0.15
        - Maximum drawdown ≈ -0.03
        - Trend slope ≈ 0.42
    *   *Seg 1 Para 6:* The asset displays moderate momentum strength with manageable downside risk. The risk-return profile suggests a balanced approach where volatility is contained relative to returns, supporting a defensive growth stance.

    *   *Seg 2 Para 1:* Over the same timeframe, the broader technology landscape experienced a distinct shift in price action. Investor sentiment leaned more aggressively toward growth assets, driven by favorable liquidity conditions. Market stability persisted as capital rotated into high-conviction equity names.
    *   *Seg 2 Para 2:* Price dynamics showed stronger upward momentum compared to peers, recording a monthly return of 0.05. The trend was steeper, indicating accelerated buying pressure and reduced hesitation among market participants.
    *   *Seg 2 Para 3:* Macro conditions mirrored the broader environment with a real interest rate of 0.52 and a yield curve of -0.28. Unemployment change held steady at -0.00. These metrics suggest a consistent discount rate environment that favors equity valuations across the sector.
    *   *Seg 2 Para 4:* Institutional capital flows intensified into large-cap technology stocks seeking yield enhancement. Risk appetite expanded as investors prioritized growth potential over defensive positioning. The macro backdrop facilitated higher risk premiums for quality assets.
    *   *Seg 2 Para 5:* The statistical profile reveals lower volatility and tighter drawdown control.
        - Monthly return ≈ 0.05
        - Monthly volatility ≈ 0.12
        - Maximum drawdown ≈ -0.02
        - Trend slope ≈ 0.90
    *   *Seg 2 Para 6:* Momentum strength is notably higher with a trend slope of 0.90. Downside risk is minimized with a maximum drawdown of -0.02. The overall risk-return profile is superior, offering enhanced returns with reduced volatility compared to the benchmark segment.

    *   *Seg 2 Final Para:* Both segments operate within an identical macroeconomic framework defined by a real interest rate of 0.52 and a yield curve of -0.28. Unemployment change remains consistent at -0.00 across both periods. Market indicators show similar returns of 0.04 and 0.05, though volatility differs at 0.15 versus 0.12. The similarity stems from shared discount-rate environments that synchronize capital flows into large-cap technology stocks. Comparable volatility regimes ensure that both assets react similarly to macro shocks despite divergent trend slopes. (Count: 96 words).

7.  **Review against Constraints:**
    *   Plain text only? Yes.
    *   Bullet points allowed? Yes (used in Para 5).
    *   No reasoning steps? Yes.
    *   Only numerical values from table? Yes.
    *   Round to 2 decimals? Yes.
    *   Write as decimals? Yes.
    *   Structure followed? Yes (6 paras per segment + final para for Seg 2).
    *   Segment 2 wording different? Yes.
    *   Highlight differences in Seg 2? Yes (slope 0.90 vs 0.42, vol 0.12 vs 0.15).
    *   Final Para 60+ words? Yes (checked count).
    *   Compare macro indicators? Yes.
    *   Compare market indicators? Yes.
    *   Explain economic mechanism? Yes.

8.  **Final Polish:** Check rounding again.
    *   0.523662 -> 0.52
    *   -0.28 -> -0.28
    *   -0.000793651 -> -0.00
    *   0.0421066 -> 0.04
    *   0.149969 -> 0.15
    *   -0.0328422 -> -0.03
    *   0.41676 -> 0.42
    *   0.0505511 -> 0.05
    *   0.121815 -> 0.12
    *   -0.0172635 -> -0.02
    *   0.897162 -> 0.90

    Looks good. Ensure no markdown headers like "## Segment 1". Just text. The prompt says "Output plain text only". I will use text headers like "Segment 1: company, start_date to end_date" as per the structure instruction "Segment X: company, start_date to end_date". Wait, the structure instruction says "Segment X: company, start_date to end_date". I should include that line at the start of each segment.

    Wait, checking the structure instruction again:
    "STRUCTURE
    Segment X: company, start_date to end_date
    Paragraph 1..."

    So I need to include the header line.

    Also, check "Write Segment 1 first, then Segment 2."

    One more check on the Final Paragraph requirement: "This explanation must be at least 60 words and must: - compare macro indicators... - compare market indicators... - explain the economic mechanism..."

    My draft for the final paragraph:
    "Both segments operate within an identical macroeconomic framework defined by a real interest rate of 0.52 and a yield curve of -0.28. Unemployment change remains consistent at -0.00 across both periods. Market indicators show similar returns of 0.04 and 0.05, though volatility differs at 0.15 versus 0.12. The similarity stems from shared discount-rate environments that synchronize capital flows into large-cap technology stocks. Comparable volatility regimes ensure that both assets react similarly to macro shocks despite divergent trend slopes."

    Word count check:
    Both(1) segments(2) operate(3) within(4) an(5) identical(6) macroeconomic(7) framework(8) defined(9) by(10) a(11) real(12) interest(13) rate(14) of(15) 0.52(16) and(17) a(18) yield(19) curve(20) of(21) -0.28.(22)
    Unemployment(23) change(24) remains(25) consistent(26) at(27) -0.00(28) across(29) both(30) periods.(31)
    Market(32) indicators(33) show(34) similar(35) returns(36) of(37) 0.04(38) and(39) 0.05,(40) though(41) volatility(42) differs(43) at(44) 0.15(45) versus(46) 0.12.(47)
    The(48) similarity(49) stems(50) from(51) shared(52) discount-rate(53) environments(54) that(55) synchronize(56) capital(57) flows(58) into(59) large-cap(60) technology(61) stocks.(62)
    Comparable(63) volatility(64) regimes(65) ensure(66) that(67) both(68) assets(69) react(70) similarly(71) to(72) macro(73) shocks(74) despite(75) divergent(76) trend(77) slopes.(78)

    78 words. Safe.

    Wait, I need to make sure I don't use markdown headers like `###`. Just plain text.
    Also, ensure "Segment X: company, start_date to end_date" is used exactly as a header line.

    Let's assemble.

    Wait, one detail: "Write numbers as decimals (do not convert to percentages)."
    My draft uses 0.52, 0.04 etc. This is correct.

    One detail on rounding: "Round numbers to 2 decimals."
    -0.000793651 -> -0.00.
    0.523662 -> 0.52.
    -0.28 -> -0.28.
    0.0421066 -> 0.04.
    0.149969 -> 0.15.
    -0.0328422 -> -0.03.
    0.41676 -> 0.42.
    0.0505511 -> 0.05.
    0.121815 -> 0.12.
    -0.0172635 -> -0.02.
    0.897162 -> 0.90.

    Looks consistent.

    Final check on Segment 2 Final Paragraph: "Explain why Segment 2 is similar to Segment 1."
    My draft explains similarity based on macro framework and discount rates. This fits.

    Ready to write.

    Wait, I need to check if I should include the header "Segment 1: MSFT (Top1), 2024-11-01 to 2024-11-30" or just "Segment 1: company, start_date to end_date".
    The prompt says: "STRUCTURE ... Segment X: company, start_date to end_date".
    Usually, this means I should replace X, company, start_date, end_date with actual values.
    So: "Segment 1: MSFT (Top1), 2024-11-01 to 2024-11-30"
    And "Segment 2: AAPL (Query), 2024-11-01 to 2024-11-30"

    Wait, looking at the data table:
    Segment 1: MSFT (Top1)
    Segment 2: AAPL (Query)
    Dates: 2024-11-01 to 2024-11-30

    I will use the specific company names provided in the table.

    One more check: "Do not output reasoning steps."
    I will ensure only the final text is output.

    One more check: "Bullet points using "-" are allowed."
    I will use them in Paragraph 5.

    One more check: "Write Segment 1 first, then Segment 2."
    Okay.

    One more check: "IMPORTANT FOR SEGMENT 2 ... Do NOT repeat Segment 1 wording."
    I have varied the wording in my draft.

    One more check: "Highlight differences in market behavior, especially trend slope (feat_trend_slope) and volatility."
    In Seg 2 Para 6, I mention slope 0.90 vs 0.42 (implicitly or explicitly) and vol 0.12 vs 0.15. I should make sure it's explicit in the text.
    In my draft Seg 2 Para 6: "Momentum strength is notably higher with a trend slope of 0.90. Downside risk is minimized with a maximum drawdown of -0.02. The overall risk-return profile is superior, offering enhanced returns with reduced volatility compared to the benchmark segment."
    This mentions slope and volatility comparison.

    Okay, proceeding to generate output.

    Wait, I need to check the rounding of -0.000793651.
    Round to 2 decimals: -0.00.
    Is -0.00 acceptable? Yes, it's a decimal representation.
    Or should it be 0.00? Usually -0.00 is technically correct for negative numbers close to zero, but 0.00 is cleaner. Given the instruction "Round numbers to 2 decimals", -0.00 is the direct result. I will use -0.00 to be precise to the sign, or 0.00 if it looks better. The table says -0.000793651. Rounding to 2 decimals gives -0.00. I will use -0.00.

    Wait, checking the table again.
    ctx_unemployment_change_mean: -0.000793651
    Rounded to 2 decimals: -0.00.

    Okay.

    Let's assemble the text.

    Segment 1: MSFT (Top1), 2024-11-01 to 2024-11-30

    Paragraph 1...
    Paragraph 2...
    Paragraph 3...
    Paragraph 4...
    Paragraph 5...
    Paragraph 6...

    Segment 2: AAPL (Query), 2024-11-01 to 2024-11-30

    Paragraph 1...
    Paragraph 2...
    Paragraph 3...
    Paragraph 4...
    Paragraph 5...
    Paragraph 6...
    Final Paragraph...

    Ensure no markdown headers like `#`. Just text.
    Ensure bullet points use `-`.

    Let's write.

    Wait, I need to make sure I don't accidentally use markdown for the headers. Just plain text lines.
    "Segment 1: MSFT (Top1), 2024-11-01 to 2024-11-30"

    Okay.

    One last check on the Final Paragraph word count.
    "Both segments operate within an identical macroeconomic framework defined by a real interest rate of 0.52 and a yield curve of -0.28. Unemployment change remains consistent at -0.00 across both periods. Market indicators show similar returns of 0.04 and 0.05, though volatility differs at 0.15 versus 0.12. The similarity stems from shared discount-rate environments that synchronize capital flows into large-cap technology stocks. Comparable volatility regimes ensure that both assets react similarly to macro shocks despite divergent trend slopes."
    Count: 78 words.
    Requirements:
    - compare macro indicators (real rate, yield curve, unemployment) -> Done.
    - compare market indicators (ret, vol, mdd, slope) -> Done (ret, vol, slope mentioned).
    - explain economic mechanism (discount-rate, flows, volatility) -> Done.
    - at least 60 words -> Done.

    Okay, ready.

    Wait, I need to check if I should include the paragraph numbers or just the text.
    "STRUCTURE ... Paragraph 1 ... Paragraph 2 ..."
    Usually, this means write the content of Paragraph 1, then Paragraph 2. I will not write "Paragraph 1:" explicitly unless it's part of the structure template. The template says "Segment X: company... Paragraph 1 — Market Regime". I will write the text directly under the segment header. I will not label "Paragraph 1" explicitly to keep it clean, but I will follow the content flow.
    Actually, looking at "STRUCTURE", it lists "Paragraph 1 — Market Regime". I should probably just write the text blocks. I will not add "Paragraph 1" labels to avoid clutter, just the text blocks separated by newlines.
    Wait, "Follow the structure exactly."
    Does it mean I need to write "Paragraph 1 — Market Regime"?
    Usually, in these prompts, it means follow the content flow. I will write the text blocks. I will not add the label "Paragraph 1" to ensure it looks like a commentary.
    However, to be safe on "Follow the structure exactly", I will check if labels are required.
    "STRUCTURE
    Segment X: company, start_date to end_date
    Paragraph 1 — Market Regime
    Describe..."
    This looks like instructions for content, not necessarily literal text to output. I will output the commentary text.
    I will separate paragraphs with blank lines.

    Wait, one detail: "Write numbers as decimals (do not convert to percentages)."
    I have done this.

    Okay, final check on Segment 2 Final Paragraph.
    "Explain why Segment 2 is similar to Segment 1."
    My text does this.

    Okay, generating output.
</think>

Segment 1: MSFT (Top1), 2024-11-01 to 2024-11-30

During the period from 2024-11-01 to 2024-11-30, the market operated within a stable macroeconomic regime characterized by cautious investor sentiment. Technology sector positioning remained constructive as large-cap names attracted steady institutional capital flows. General market stability was maintained despite external volatility pressures.

Price behavior exhibited a positive trajectory with a monthly return of 0.04. The asset demonstrated resilience, capturing upside momentum while managing downside exposure effectively throughout the month.


In [222]:
from pathlib import Path

raw = Path("analysis.md").read_text(errors="ignore")


def extract_final_output(text: str) -> str:

    if "</think>" in text:
        text = text.split("</think>")[-1]

    if "<<<BEGIN_FINAL>>>" in text and "<<<END_FINAL>>>" in text:
        text = text.split("<<<BEGIN_FINAL>>>", 1)[1].split("<<<END_FINAL>>>", 1)[0]

    return text.strip()


final_text = extract_final_output(raw)

Path("final.md").write_text(final_text, encoding="utf-8")

print("saved final.md, chars =", len(final_text))

print("\n--- preview ---\n")
print("\n".join(final_text.splitlines()[:120]))

saved final.md, chars = 3703

--- preview ---

Segment 1: MSFT (Top1), 2024-11-01 to 2024-11-30

During the period from 2024-11-01 to 2024-11-30, the market operated within a stable macroeconomic regime characterized by cautious investor sentiment. Technology sector positioning remained constructive as large-cap names attracted steady institutional capital flows. General market stability was maintained despite external volatility pressures.

Price behavior exhibited a positive trajectory with a monthly return of 0.04. The asset demonstrated resilience, capturing upside momentum while managing downside exposure effectively throughout the month.

Macro indicators reflected a neutral discount rate environment with a real interest rate of 0.52. The yield curve stood at -0.28, suggesting mild inversion, while unemployment change remained near -0.00. These conditions imply stable economic fundamentals with limited pressure on valuation multiples.

This macro regime supports risk-on positioning among institutional investors. Capital flows continue to favor large-cap technology stocks as discount rates remain contained. Investor risk appetite is sustained by the perceived safety of established market leaders.

The statistical profile indicates moderate volatility and controlled drawdowns.
- Monthly return ≈ 0.04
- Monthly volatility ≈ 0.15
- Maximum drawdown ≈ -0.03
- Trend slope ≈ 0.42

The asset displays moderate momentum strength with manageable downside risk. The risk-return profile suggests a balanced approach where volatility is contained relative to returns, supporting a defensive growth stance.

Segment 2: AAPL (Query), 2024-11-01 to 2024-11-30

Over the same timeframe, the broader technology landscape experienced a distinct shift in price action. Investor sentiment leaned more aggressively toward growth assets, driven by favorable liquidity conditions. Market stability persisted as capital rotated into high-conviction equity names.

Price dynamics showed stronger upward momentum compared to peers, recording a monthly return of 0.05. The trend was steeper, indicating accelerated buying pressure and reduced hesitation among market participants.

Macro conditions mirrored the broader environment with a real interest rate of 0.52 and a yield curve of -0.28. Unemployment change held steady at -0.00. These metrics suggest a consistent discount rate environment that favors equity valuations across the sector.

Institutional capital flows intensified into large-cap technology stocks seeking yield enhancement. Risk appetite expanded as investors prioritized growth potential over defensive positioning. The macro backdrop facilitated higher risk premiums for quality assets.

The statistical profile reveals lower volatility and tighter drawdown control.
- Monthly return ≈ 0.05
- Monthly volatility ≈ 0.12
- Maximum drawdown ≈ -0.02
- Trend slope ≈ 0.90

Momentum strength is notably higher with a trend slope of 0.90. Downside risk is minimized with a maximum drawdown of -0.02. The overall risk-return profile is superior, offering enhanced returns with reduced volatility compared to the benchmark segment.

Both segments operate within an identical macroeconomic framework defined by a real interest rate of 0.52 and a yield curve of -0.28. Unemployment change remains consistent at -0.00 across both periods. Market indicators show similar returns of 0.04 and 0.05, though volatility differs at 0.15 versus 0.12. The similarity stems from shared discount-rate environments that synchronize capital flows into large-cap technology stocks. Comparable volatility regimes ensure that both assets react similarly to macro shocks despite divergent trend slopes.

[ Prompt: 4581.8 t/s | Generation: 151.7 t/s ]

>

In [223]:
import os
print(os.getcwd())

/content/Finance-Research/Finance-Research/Finance-Research/Finance-Research